setwd('/Volumes/OSX/Users/pichugin/Projects/Fragmentation with costs/Local simulations/Classes abundance and groups size/True random delay cost 2020/')

Write2File=2


# Size of figure
pdfSizeX=5
pdfSizeY=5

## margin parameters
Bottom=3.5
Left=4
Top=0.5
Right=0.5


#palette generated by iwanthue
CLR_bin <- "#88d08f"
CLR_equal <- "#d9aa5a"
CLR_seed <- "#ca5159"
CLR_other <- "#c595cd"


Data=read.csv("Combined_Delay_Scan.txt")
Data=Data[,3:dim(Data)[2]]

Binaries_ID = read.csv(file = "Binaries_6_ID.dat")
Equal_ID = read.csv(  file = "Equal_6_ID.dat")
Seed_ID = read.csv(  file = "Seeding_6_ID.dat")
Other_ID = read.csv(   file = "Other_6_ID.dat")


ClassPartitions=matrix(0, nrow = 4, ncol = dim(Data)[2])

for(Risk in 1:dim(Data)[2]){
  print(Risk)
  
  Slice <- Data[, Risk]
  
  Binary_num <- 0
  Equal_Num <- 0 
  Seed_Num <- 0
  Other_Num <- 0
  
  for(Entry in Slice){
    if(Entry %in% Binaries_ID[,1]){
      Binary_num <- Binary_num + 1
    }
    
    if(Entry %in% Equal_ID[,1]){
      Equal_Num <- Equal_Num + 1
    }
    
    if(Entry %in% Seed_ID[,1]){
      Seed_Num <- Seed_Num + 1
    }
    
    if(Entry %in% Other_ID[,1]){
      Other_Num <- Other_Num + 1
    }
  }
  
  Total_Num <- Binary_num + Equal_Num + Seed_Num + Other_Num 
  ClassPartitions[1, Risk] <- Binary_num/Total_Num
  ClassPartitions[2, Risk] <- Equal_Num/Total_Num
  ClassPartitions[3, Risk] <- Seed_Num/Total_Num
  ClassPartitions[4, Risk] <- Other_Num/Total_Num
  
}


if(Write2File==1){svg(file="ClassesVsDelay_v9.svg", height=pdfSizeY, width=pdfSizeX)}
if(Write2File==2){cairo_pdf(file="ClassesVsDelay_v9.pdf", height=pdfSizeY, width=pdfSizeX)}

# par(pty="s", mgp=c(2.5,0.6,0.0), xpd=T, mar=c(Bottom,Left, Top, Right), cex.axis=1.1, bty="o")
par(pty="s", mgp=c(2.4, 0.6, 0.0), xpd=T, mar=c(Bottom,Left, Top, Right), cex.axis=1.4, bty="o", las = 1)

CLR_list=c(CLR_bin, CLR_equal, CLR_seed, CLR_other)

MyBP2<-barplot(ClassPartitions[,], col=CLR_list, axes=F, ann=F, xlab="Fragmentation delay", ylab="Fraction of environments", cex.lab=1.6, xaxs="i", yaxs="i", border=NA, space=0)

# Xarray <- seq(0, 20, length.out = dim(Data)[2])
# plot( c(0,20), c(0,1), type = "l", col="white", lwd = 1, ylim=c(0,1), xaxs="i", yaxs="i", ann=F)
# lines(Xarray, ClassPartitions[1,], col=CLR_list[1], lwd=5)
# lines(Xarray, ClassPartitions[2,], col=CLR_list[2], lwd=5)
# lines(Xarray, ClassPartitions[3,], col=CLR_list[3], lwd=5)
# lines(Xarray, ClassPartitions[4,], col=CLR_list[4], lwd=5)
# title(xlab="Fragmentation delay", ylab="Fraction of environments", cex.lab=1.6)
 
SQ=seq(0,1, length.out = 6)
SQT=c("0.0", "0.2", "0.4", "0.6", "0.8", "1.0")
axis(2, at=SQ, labels=SQT)

SQX=seq(0, 20, length.out=5)
PosX=SQX/length(SQX)*dim(ClassPartitions)[2]
axis(1, at=10*SQX, labels=SQX)


if(Write2File>0){dev.off()}

# dev.off()




# LC_ID <- read.csv("LC_ID_FFLL_full.dat")
# 
# MeanFragSize <- c()
# StdFragSize <- c()
# MeanOffNum <- c()
# StdOffNum <- c()
# MeanSizeOff <- c()
# StdSizeOff <- c()
# 
# for(Cost in 1:dim(Data)[2]){
#   print(Cost)
#   Slice <- Data[,Cost]
#   FragSize <- c()
#   OffNum <- c()
#   SizeOff <- c()
#   for(Entry in 1:length(Slice)){
#     E_ID <- Slice[Entry]
#     Index <- which(LC_ID$ID == E_ID)
#     FragSize <- c(FragSize, LC_ID$Combined.size[Index] - 1)
#     OffNum <- c(OffNum, LC_ID$Offspring.number[Index])
#     SizeOff <- c(SizeOff, LC_ID$Combined.size[Index] / LC_ID$Offspring.number[Index])
#   }
#   MeanFragSize <- c(MeanFragSize, mean(FragSize))
#   StdFragSize <- c(StdFragSize, sqrt(var(FragSize)))
#   MeanOffNum <- c(MeanOffNum, mean(OffNum))
#   StdOffNum <- c(StdOffNum, sqrt(var(OffNum)))
#   MeanSizeOff <- c(MeanSizeOff, mean(SizeOff))
#   StdSizeOff <- c(StdSizeOff, sqrt(var(SizeOff)))
# }
# 
# 
# 
# 
# CLR_ParentSize <- "#32736d"
# CLR_OffspringNum <- "#f7acba"
# 
# Xseq <- seq(0,20, length.out = length(MeanFragSize))
# SubsetSeq <- seq(1, length(Xseq), 20)
# DX <- 0.4
# 
# # svg(file="StatisticsSizes_Delay_v3.svg", height=pdfSizeY, width=pdfSizeX)
# ## make a negative map
# if(Write2File==1){svg(file = "StatisticsSizes_Delay_v5.svg", height=pdfSizeY, width=pdfSizeX)}
# if(Write2File==2){cairo_pdf(file="StatisticsSizes_Delay_v5.pdf", height=pdfSizeY, width=pdfSizeX)}
# 
# par(pty="s", mgp=c(2.5,0.6,0.0), xpd=T, mar=c(Bottom,Left, Top, Right+2), cex.axis=1.1, tcl = -0.5)
# plot(c(0,20), c(0,20), type="l", col="white", ann=F, xaxt="n", yaxt="n")
# 
# Ylow <- MeanFragSize-StdFragSize
# YHigh <- MeanFragSize+StdFragSize
# Xleft <- Xseq - DX
# Xright <- Xseq + DX
# points(Xseq, MeanFragSize, col=CLR_ParentSize, pch=16)
# for(i in 1:length(SubsetSeq)){
#   Ind <- SubsetSeq[i]
#   lines(c(Xseq[Ind], Xseq[Ind]), c(Ylow[Ind], YHigh[Ind]), col=CLR_ParentSize)
#   lines(c(Xleft[Ind], Xright[Ind]), c(Ylow[Ind], Ylow[Ind]), col=CLR_ParentSize)
#   lines(c(Xleft[Ind], Xright[Ind]), c(YHigh[Ind], YHigh[Ind]), col=CLR_ParentSize)
# }
# 
# # SubsetSeq <- seq(10, length(Xseq), 20)
# # Ylow <- MeanOffNum-StdOffNum
# # YHigh <- MeanOffNum+StdOffNum
# # Xleft <- Xseq - DX
# # Xright <- Xseq + DX
# # points(Xseq, MeanOffNum, col=CLR_OffspringNum, pch=16)
# # for(i in 1:length(SubsetSeq)){
# #   Ind <- SubsetSeq[i]
# #   lines(c(Xseq[Ind], Xseq[Ind]), c(Ylow[Ind], YHigh[Ind]), col=CLR_OffspringNum)
# #   lines(c(Xleft[Ind], Xright[Ind]), c(Ylow[Ind], Ylow[Ind]), col=CLR_OffspringNum)
# #   lines(c(Xleft[Ind], Xright[Ind]), c(YHigh[Ind], YHigh[Ind]), col=CLR_OffspringNum)
# # }
# 
# SubsetSeq <- seq(10, length(Xseq), 20)
# Ylow <- MeanSizeOff-StdSizeOff
# YHigh <- MeanSizeOff+StdSizeOff
# Xleft <- Xseq - DX
# Xright <- Xseq + DX
# points(Xseq, MeanSizeOff, col=CLR_OffspringNum, pch=16)
# for(i in 1:length(SubsetSeq)){
#   Ind <- SubsetSeq[i]
#   lines(c(Xseq[Ind], Xseq[Ind]), c(Ylow[Ind], YHigh[Ind]), col=CLR_OffspringNum)
#   lines(c(Xleft[Ind], Xright[Ind]), c(Ylow[Ind], Ylow[Ind]), col=CLR_OffspringNum)
#   lines(c(Xleft[Ind], Xright[Ind]), c(YHigh[Ind], YHigh[Ind]), col=CLR_OffspringNum)
# }
# 
# axis(2, at=c(0,5,10,15,20), labels=c(0,5,10,15,20))
# # axis(1, at=c(0,5,10,15,20), labels=c(0,5,10,15,20))
# par(tcl = 0.5)
# axis(1, at=c(0,5,10,15,20), labels = F)
# # axis(4, at=c(0,5,10,15,20), labels=c(0,5,10,15,20), col.axis=CLR_OffspringNum, col=CLR_OffspringNum)
# # mtext("Offspring number", side=4, line=2, cex=1.6, col=CLR_OffspringNum)
# # mtext("Size at fragmentation", side=2, line=2, cex=1.6, col=CLR_ParentSize)
# mtext("Size", side=2, line=2, cex=1.6)
# # mtext("Fragmentation delay", side=1, line=2, cex=1.6)
# 
# if(Write2File>0){dev.off()}
# # dev.off()
# 
# 
# #
# # CLR_ParentSize <- "#32736d"
# # CLR_OffspringNum <- "#f7acba"
# #
# # Xseq <- seq(0,20, length.out = length(MeanFragSize))
# # SubsetSeq <- seq(1, length(Xseq), 20)
# # DX <- 0.4
# #
# # # svg(file="StatisticsSizes_Delay.svg", height=pdfSizeY, width=pdfSizeX)
# #
# # par(pty="s", mgp=c(2.5,0.6,0.0), xpd=T, mar=c(Bottom,Left, Top, Right+2), cex.axis=1.1)
# # plot(c(0,20), c(0,20), type="l", col="white", ann=F, xaxt="n", yaxt="n")
# #
# # Ylow <- MeanFragSize-StdFragSize
# # YHigh <- MeanFragSize+StdFragSize
# # Xleft <- Xseq - DX
# # Xright <- Xseq + DX
# # points(Xseq, MeanFragSize, col=CLR_ParentSize, pch=16)
# # for(i in 1:length(SubsetSeq)){
# #   Ind <- SubsetSeq[i]
# #   lines(c(Xseq[Ind], Xseq[Ind]), c(Ylow[Ind], YHigh[Ind]), col=CLR_ParentSize)
# #   lines(c(Xleft[Ind], Xright[Ind]), c(Ylow[Ind], Ylow[Ind]), col=CLR_ParentSize)
# #   lines(c(Xleft[Ind], Xright[Ind]), c(YHigh[Ind], YHigh[Ind]), col=CLR_ParentSize)
# # }
# #
# # SubsetSeq <- seq(10, length(Xseq), 20)
# # Ylow <- MeanOffNum-StdOffNum
# # YHigh <- MeanOffNum+StdOffNum
# # Xleft <- Xseq - DX
# # Xright <- Xseq + DX
# # points(Xseq, MeanOffNum, col=CLR_OffspringNum, pch=16)
# # for(i in 1:length(SubsetSeq)){
# #   Ind <- SubsetSeq[i]
# #   lines(c(Xseq[Ind], Xseq[Ind]), c(Ylow[Ind], YHigh[Ind]), col=CLR_OffspringNum)
# #   lines(c(Xleft[Ind], Xright[Ind]), c(Ylow[Ind], Ylow[Ind]), col=CLR_OffspringNum)
# #   lines(c(Xleft[Ind], Xright[Ind]), c(YHigh[Ind], YHigh[Ind]), col=CLR_OffspringNum)
# # }
# #
# # axis(2, at=c(0,5,10,15,20), labels=c(0,5,10,15,20))
# # axis(1, at=c(0,5,10,15,20), labels=c(0,5,10,15,20))
# # # axis(4, at=c(0,5,10,15,20), labels=c(0,5,10,15,20), col.axis=CLR_OffspringNum, col=CLR_OffspringNum)
# # # mtext("Offspring number", side=4, line=2, cex=1.6, col=CLR_OffspringNum)
# # # mtext("Size at fragmentation", side=2, line=2, cex=1.6, col=CLR_ParentSize)
# # mtext("Size", side=2, line=2, cex=1.6)
# # mtext("Reproduction delay", side=1, line=2, cex=1.6)
# #
# # # dev.off()

